stages:
- name: Build The Images
  steps:
  - publishImageConfig:
      dockerfilePath: daemon/Dockerfile
      buildContext: daemon
      tag: johncclayton/ldap-auth-daemon:1.3.0
      pushRemote: true
      registry: index.docker.io
  - publishImageConfig:
      dockerfilePath: webapp/Dockerfile
      buildContext: webapp
      tag: johncclayton/ldap-auth-webapp:1.3.0
      pushRemote: true
      registry: index.docker.io
timeout: 600
notification: {}
