version: '3.2'

services:
  proxy: 
    image: nginx:1.15-alpine
    volumes:
      - ./nginx-ldap-auth.conf:/etc/nginx/nginx.conf
      - ./:/etc/nginx/logs

    ports:
      - "8081:8081"

  auth:
    build: daemon
    environment:       
      - URL=${URL:?URL is required}
      - BASE=${BASE:?BASE is required}
      - BIND_DN=${BIND_DN:?BIND_DN is required}
      - BIND_PASS=${BIND_PASS:?BIND_PASS is required}
      - COOKIE=${COOKIE:?COOKIE is required}
      - FILTER=${FILTER:?FILTER is required}
      - REALM=${REALM:?REALM is required}
      - CRYPTO_RANDOM_16=${RANDOM16:?RANDOM16 is required}

    ports:
      - "8888:8888"

  webapp:
    build: webapp
    environment:       
      - CRYPTO_RANDOM_16=${RANDOM16:?RANDOM16 is required}
    ports:
      - "9000:9000"


 
